name: Manual trigger workflow
# workflow dispatch is marking this job to be executed only when manually triggered
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run suite on'
        required: true
        default: 'qa'
      priority:
        description: 'Priority level'
        required: true
        default: '@P0'
jobs:
  test:
    timeout-minutes: 60 # this tells the maximum time allowed for a job to take and get completed
    runs-on: ubuntu-latest # this defines which machine to use on github
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
      PRIORITY: ${{ github.event.inputs.priority }}
    steps: # add the steps
      - uses: actions/checkout@v3 # it defines a unit of code which we are using to pull code from repo
      - uses: actions/setup-node@v3 # this set up the node on the machine
        with:
          node-version: 18 # this define which version of node to install and setup on the machine
      - name: Install dependencies # giving each step a name (like installing depdendencies)
        run: npm ci # this is clean install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          if [ "${PRIORITY}" = "@P0" ]; then
            npm run test:demo
          else
            npm run test:whole
          fi
        # Upload the artifact
        post-actions:
          - name: Upload artifact
            uses: actions/upload-artifact@v2
            with:
              name: playwright-report
              path: playwright-report/

          - name: Publish Artifacts
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: playwright-report
